// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @notice Interface for the on-chain Poseidon(2) contract generated by
/// circomlibjs's `poseidonContract.createCode(2)` — raw EVM assembly, deployed
/// via DeployShieldedPool.s.sol from contracts/script/artifacts/PoseidonT3.bytecode.txt,
/// not written from Solidity source. Exists so ShieldedPool.sol's on-chain
/// Merkle tree hashes with the exact same Poseidon parameters
/// shielded_spend.circom uses in-circuit — a different hash function for the
/// tree would make every Merkle proof the circuit verifies meaningless.
interface IPoseidonT3 {
    function poseidon(uint256[2] calldata input) external pure returns (uint256);
}
