// SPDX-License-Identifier: GPL-3.0
/*
    Copyright 2021 0KIMS association.

    This file is generated with [snarkJS](https://github.com/iden3/snarkjs).

    snarkJS is a free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    snarkJS is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
    License for more details.

    You should have received a copy of the GNU General Public License
    along with snarkJS. If not, see <https://www.gnu.org/licenses/>.
*/

/// @notice Auto-generated by snarkjs from circuits/src/transition.circom — do
/// not hand-edit. Regenerate via circuits/build if the circuit ever changes.
/// Upstream file carries its own GPL-3.0 header above (snarkjs default); this
/// generated artifact keeps that license, distinct from the MIT license on
/// the rest of this repo's hand-written contracts. Trusted setup as of this
/// version is anchored to the real, public, multi-party Hermez Perpetual
/// Powers of Tau ceremony (powersOfTau28_hez_final_14.ptau, see
/// circuits/build/README.md) rather than a single-party one.
pragma solidity ^0.8.24;

contract Groth16Verifier {
    // Scalar field size
    uint256 constant r    = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    // Base field size
    uint256 constant q   = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    // Verification Key data
    uint256 constant alphax  = 20491192805390485299153009773594534940189261866228447918068658471970481763042;
    uint256 constant alphay  = 9383485363053290200918347156157836566562967994039712273449902621266178545958;
    uint256 constant betax1  = 4252822878758300859123897981450591353533073413197771768651442665752259397132;
    uint256 constant betax2  = 6375614351688725206403948262868962793625744043794305715222011528459656738731;
    uint256 constant betay1  = 21847035105528745403288232691147584728191162732299865338377159692350059136679;
    uint256 constant betay2  = 10505242626370262277552901082094356697409835680220590971873171140371331206856;
    uint256 constant gammax1 = 11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 constant gammax2 = 10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 constant gammay1 = 4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 constant gammay2 = 8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 constant deltax1 = 19948143177584592816045164622500312734990177059480951224606577962552022453199;
    uint256 constant deltax2 = 7692534755593567795258227734138850490685062893130491033629610196747704138425;
    uint256 constant deltay1 = 11328489320976801968432659107090407325507845160074485994016038307478684462801;
    uint256 constant deltay2 = 19777382880665174455069318603850083400709543695629710487481940375846932590454;

    
    uint256 constant IC0x = 11345916523708321164257378234291905450190470385858271218891328327354333170206;
    uint256 constant IC0y = 20347810998084591734414079204991033423338752009412667828925909469676783446512;
    
    uint256 constant IC1x = 3710288209957070977881824446252503378612188747794630016863067972572207591092;
    uint256 constant IC1y = 15753402112975428558096680187112287829783453740028262890984499385671688539658;
    
    uint256 constant IC2x = 4417447504489562447982262931093495038952047637392745343678581354249934373224;
    uint256 constant IC2y = 6103012511260527090774688345629891131108696264870041109960334041205005603561;
    
    uint256 constant IC3x = 15838312863091183998273222377099561435350207976528531812736739850731172426318;
    uint256 constant IC3y = 4468990886196489539689066809630179170582455280428312515932103754788719818675;
    
    uint256 constant IC4x = 14210404977581080545594854260331345144281754908656785347064059671195149232814;
    uint256 constant IC4y = 8510694737791573247329504684763746485759979649902193397010603923659534359555;
    
    uint256 constant IC5x = 21115117661060450597053634974694703664330523479534700909423181325528960913166;
    uint256 constant IC5y = 10043317901040894455046030846517896399695899675768143171305218952106807355559;
    
    uint256 constant IC6x = 17125024857823229939053465188670086428630148973735193514370584465797122407644;
    uint256 constant IC6y = 2608562231023518051536916282722522958007123039478337944949070088099606665267;
    
    uint256 constant IC7x = 3263775573964431154984090937941004176748196188646768005236024934201444475267;
    uint256 constant IC7y = 8431653561542954288876382997317386217277915209908387551691381501582607001479;
    
    uint256 constant IC8x = 5464043854155699413954089943630746778566425753264244008426866041961739182186;
    uint256 constant IC8y = 13521748457739641720808700026521063425640144224490869546384093292520352905865;
    
    uint256 constant IC9x = 17533780925637048033512074477880540997409760277864547590238026094396232899342;
    uint256 constant IC9y = 9356141264050187766967306765275915946143453396262246002884104492985028519637;
    
    uint256 constant IC10x = 11587428408779371270173871529645358256354594758203815199796876998587088549170;
    uint256 constant IC10y = 20097498809586888342932959932781918130049047818421300019942570620426846194333;
    
 
    // Memory data
    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant pLastMem = 896;

    function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[10] calldata _pubSignals) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }
            
            // G1 function to multiply a G1 value(x,y) to value in an address
            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Compute the linear combination vk_x
                
                g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                
                g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                
                g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                
                g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))
                
                g1_mulAccC(_pVk, IC5x, IC5y, calldataload(add(pubSignals, 128)))
                
                g1_mulAccC(_pVk, IC6x, IC6y, calldataload(add(pubSignals, 160)))
                
                g1_mulAccC(_pVk, IC7x, IC7y, calldataload(add(pubSignals, 192)))
                
                g1_mulAccC(_pVk, IC8x, IC8y, calldataload(add(pubSignals, 224)))
                
                g1_mulAccC(_pVk, IC9x, IC9y, calldataload(add(pubSignals, 256)))
                
                g1_mulAccC(_pVk, IC10x, IC10y, calldataload(add(pubSignals, 288)))
                

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(add(pMem, pVk)))
                mstore(add(_pPairing, 416), mload(add(pMem, add(pVk, 32))))


                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)


                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, pLastMem))

            // Validate that all evaluations ∈ F
            
            checkField(calldataload(add(_pubSignals, 0)))
            
            checkField(calldataload(add(_pubSignals, 32)))
            
            checkField(calldataload(add(_pubSignals, 64)))
            
            checkField(calldataload(add(_pubSignals, 96)))
            
            checkField(calldataload(add(_pubSignals, 128)))
            
            checkField(calldataload(add(_pubSignals, 160)))
            
            checkField(calldataload(add(_pubSignals, 192)))
            
            checkField(calldataload(add(_pubSignals, 224)))
            
            checkField(calldataload(add(_pubSignals, 256)))
            
            checkField(calldataload(add(_pubSignals, 288)))
            

            // Validate all evaluations
            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
             return(0, 0x20)
         }
     }
 }
